### ISSUE TITLE
First and last name are nil

### ISSUE THREAD

**Issue by willc0de4food** [nhosoya/omniauth-apple#13]
Hello. I'm working on an implementation to use this gem with Devise, and everything is working. The problem I'm facing is that, although I'm requesting the user's name, and it shows up as something I'm requesting on the Apple oauth, the name is nil that gets returned from the gem. Is this a known issue? Any fix for it?

**Comment by sebfie** [comment]
+1

**Comment by jeffsawatzky** [comment]
This could be because you have already authorized the app. Apple only sends the user object the first time the user authorizes the app. Subsequent authorizations don't send the user object.

https://developer.apple.com/documentation/signinwithapplejs/configuring_your_webpage_for_sign_in_with_apple#3331292

The user object is what contains the first/last name.

Also, the id_token that apple gives out never seems to contain the first/name info, so that means the only time you can get this is the first time you authorize the app.

**Comment by willc0de4food** [comment]
I am aware of this and tested multiple times deauthorize good the app. Never got the name.

**Comment by sdhull** [comment]
We seem to have observed an issue where if you authenticate with TouchID, then everything in the OmniAuth hash is `nil` (email, first name, last name), but if you authenticate with your Apple email & pw, everything is populated. We're still trying to figure it out, any help would be appreciated.

**Comment by rickstergg** [comment]
@sdhull , same thread as you, I'll share my findings if I come up with any, I had tried the scope encoding commit that references this issue, but we're still seeing the email coming up as `null`, will report back with any news!

**Comment by JonathanVeg** [comment]
I'm receiving the name as user e-mail. Looking in the gem it sets the name with user's email when the name do not came from apple validation.

I'm receiving it even in the first access (after removing the app from my account, having to accept and decide if I'll share my email or not).

Any solution? Thanks.

**Comment by nov** [comment]
hope this merged, or do the same in your app.
https://gitlab.com/oauth-xx/oauth2/-/merge_requests/633
